name: 'Setup TFLint'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  default:
    name: default
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Action
      uses: ./
    - name: Validate
      run: tflint -v
  versions:
    name: tflint_version (${{ matrix.tflint_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tflint_version: ['v0.24.1', latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Action
      uses: ./
      with:
        tflint_version: ${{ matrix.tflint_version }}
    - name: Validate
      if: matrix.tflint_version != 'latest'
      run: |-
        version='${{ matrix.tflint_version }}'
        tflint -v | grep ${version:1}
    - name: Validate
      if: matrix.tflint_version == 'latest'
      run: tflint -v
