name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: actions/setup-node@v2
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
          commit_message: update dist
          file_pattern: dist/*.js
