name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
  
  integration:
    name: Integration test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Action
      uses: ./
    - name: Validate
      run: tflint -v
  
  integration-versions:
    name: 'Integration test (tflint_version: ${{ matrix.tflint_version }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tflint_version: ['v0.24.1', latest]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Action
      uses: ./
      with:
        tflint_version: ${{ matrix.tflint_version }}
    - name: Validate
      if: matrix.tflint_version != 'latest'
      run: |-
        version='${{ matrix.tflint_version }}'
        tflint -v | grep ${version:1}
    - name: Validate
      if: matrix.tflint_version == 'latest'
      run: tflint -v
